version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  target-branch: main
  assignees:
  - qmenoret
  labels:
  - dependencies
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.130
    - 0.0.132
    - 0.0.134
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: ts-loader
    versions:
    - 8.0.16
    - 8.0.18
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
